name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:

  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]
        platform: [ x64, arm64 ]

    env:
      Configuration: ${{ matrix.configuration }}
      Platform: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: SHA
        id: sha
        run: echo "sha=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_OUTPUT

      - name: Build
        run: |
          $sha = "${{ steps.sha.outputs.sha }}"
          New-Item -Path "build/NonsPlayer/" -Type Directory
          msbuild src/NonsPlayer.Launcher "-property:Configuration=$env:Configuration;Platform=$env:Platform;OutDir=$(Resolve-Path "build/NonsPlayer/")"
          dotnet publish src/NonsPlayer -c Release -r "win10-$env:Platform" -o "build/NonsPlayer/app-build.$sha" -p:Platform=$env:Platform -p:Version="0.0.1-build.$sha" -p:DefineConstants=CI -p:PublishReadyToRun=true -p:UseRidGraph=true;
          Add-Content "build/NonsPlayer/version.ini" -Value "app_folder=app-build.$sha`r`nexe_name=NonsPlayer.exe"
          Remove-Item "build/NonsPlayer/NonsPlayer.pdb" -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: NonsPlayer${{ matrix.configuration }}_${{ matrix.platform }}_${{ steps.sha.outputs.sha }}
          path: build/NonsPlayer/